### ISSUE TITLE
Project Design Documents

### ISSUE THREAD

**Issue by diazren** [diazren/cplusplus_projects#1]
We need to document and list what we're going to do for project one.

- What are we going to do?
- What tools are we going to use?
- What is our schedule for this effort?

**Comment by bjdominguez23** [comment]
Things that we are wanting to accomplish in this project collaboration
- To develop a small game application that involves using a custom built API 

Tools that we might need 
- Using Visual Studio/Python
- Using Github to share and edit code 

Type of schedule we want to use in developing the said project

- Still to be determined
- Possibly meeting once a week via Zoom

**Comment by diazren** [comment]
Late to the party.. so this is a good start.

**Comment by diazren** [comment]
Too old.
